services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
        command: bash -c "php artisan migrate"
        depends_on:
            -   mariadb
        env_file: ".env.example"
    mariadb:
        image: 'mariadb:11'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'laravel'
            MYSQL_USER: 'sail'
            MYSQL_PASSWORD: 'password'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sail-mariadb:/var/lib/mysql'
            - './vendor/laravel/sail/database/mariadb/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - healthcheck.sh
                - '--connect'
                - '--innodb_initialized'
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-mariadb:
        driver: local
